services:
  db: 
    image: postgres
    container_name: db
    ports:
      - 6222:5432
    env_file:
      - .env

  node:
    container_name: practice
    build: .
    ports:
      - 5009:5001
    env_file:
      - .env
    depends_on: 
      - db

  